=== Nada98Sakr/ITI/XML/Lab3/Assignment1/employee.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employees">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="employee" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
                <xs:sequence>
                <xs:element type="xs:string" name="name"/>
                <xs:element name="phones">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="phone" maxOccurs="unbounded" minOccurs="0">
                        <xs:complexType>
                            <xs:simpleContent>
                            <xs:extension base="xs:int">
                                <xs:attribute type="xs:string" name="type" use="optional"/>
                            </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="addresses">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="address" maxOccurs="unbounded" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                            <xs:element type="xs:string" name="street"/>
                            <xs:element type="xs:string" name="buildingNumber"/>
                            <xs:element type="xs:string" name="Region"/>
                            <xs:element type="xs:string" name="city"/>
                            <xs:element type="xs:string" name="country"/>
                            </xs:sequence>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element type="xs:string" name="email"/>
                </xs:sequence>
                <xs:attribute type="xs:byte" name="isbn" use="optional"/>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
    </xs:schema><xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employees">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="employee" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
                <xs:sequence>
                <xs:element type="xs:string" name="name"/>
                <xs:element name="phones">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="phone" maxOccurs="unbounded" minOccurs="0">
                        <xs:complexType>
                            <xs:simpleContent>
                            <xs:extension base="xs:int">
                                <xs:attribute type="xs:string" name="type" use="optional"/>
                            </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="addresses">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="address" maxOccurs="unbounded" minOccurs="0">
                        <xs:complexType>
                            <xs:sequence>
                            <xs:element type="xs:string" name="street"/>
                            <xs:element type="xs:string" name="buildingNumber"/>
                            <xs:element type="xs:string" name="Region"/>
                            <xs:element type="xs:string" name="city"/>
                            <xs:element type="xs:string" name="country"/>
                            </xs:sequence>
                        </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element type="xs:string" name="email"/>
                </xs:sequence>
                <xs:attribute type="xs:byte" name="isbn" use="optional"/>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Nada98Sakr/ITI/XML/Lab3/Assignment1/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./employee.css" ?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/ITI/ITI%20-%20Open%20Source%20Development/XML%20Fundamentals/Lab3/employees%20XSD%20Schema/employee.xsd">
	<employee isbn="1">
		<name>Nada</name>
		<phones>
			<phone type="home">0312345678</phone>
			<phone type="work">0391111567</phone>
			<phone type="mobile">01011145678</phone>
		</phones>
		<addresses>
			<address>
				<street>st1,</street> 
				<buildingNumber>21,</buildingNumber> 
				<Region>Sidi Bishr,</Region> 
				<city>Alex,</city> 
				<country>Egypt.</country>
			</address> 
			<address>
				<street>st2,</street> 
				<buildingNumber>21,</buildingNumber> 
				<Region>AlMndra,</Region> 
				<city>Alex,</city> 
				<country>Egypt.</country>
			</address>
		</addresses>
		<email>nada@gmail.com</email>
	</employee>
	<employee isbn="1">
		<name>Nourhan</name>
		<phones>
			<phone type="home">0312345678</phone>
			<phone type="work">0391234567</phone>
			<phone type="mobile">01011111178</phone>
		</phones>
		<addresses>
			<address>
				<street>st1,</street> 
				<buildingNumber>no1,</buildingNumber> 
				<Region>Sidi Bishr,</Region> 
				<city>Alex,</city> 
				<country>Egypt.</country>
			</address> 
		</addresses>
		<email>nourhan@gmail.com</email>
	</employee>
</employees>
